# Google Drive

In [1]:
####################################
#
#  ADD THIS TO EVERY COLAB FILE!
#
####################################

from google.colab import drive
drive.mount('/content/drive')

import drive.Shareddrives.GPTJ.project.settings as settings

PATH_PROJECT = settings.PATH_PROJECT
PATH_DATA = settings.PATH_DATA

Mounted at /content/drive


In [2]:
! cd $PATH_PROJECT && pip install -q -r requirements.txt

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 143 kB 5.0 MB/s 
     |████████████████████████████████| 55.9 MB 1.2 MB/s 
     |████████████████████████████████| 85 kB 5.5 MB/s 
     |████████████████████████████████| 72 kB 1.4 MB/s 
     |████████████████████████████████| 7.6 MB 50.0 MB/s 
     |████████████████████████████████| 182 kB 79.2 MB/s 
     |████████████████████████████████| 1.3 MB 45.9 MB/s 
     |████████████████████████████████| 451 kB 65.2 MB/s 
     |████████████████████████████████| 212 kB 66.8 MB/s 
     |████████████████████████████████| 132 kB 74.9 MB/s 
     |████████████████████████████████| 127 kB 55.3 MB/s 


# Metrics Multi

In [3]:
import evaluate
import seaborn as sn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import drive.Shareddrives.GPTJ.project.metrics as metrics


def format(n):
    n = round(n, 4)
    return str(n).replace('.', ',')


def results(p):
    try:    
        df = pd.read_csv(PATH_DATA + p)
        predictions = list(df['pred_all'])
        references = list(df['ref'])
        # print('predictions', predictions)
        # print('references', references)
        print('len(references)', len(references))
        m = metrics.get_metrics(references, predictions)
        print('good', m['good'])
        print('bad', m['bad'])
        print('matrix', m['matrix'])
        print('acc', 'f1')
        print(format(m['accuracy']) + ';' + ';'.join([format(x) for x in m['f1']]))
    except:
        print('not done')

# matrix = m['matrix']
# matrix_100 = 100* matrix / matrix.astype(np.float).sum(axis=1)
# print(m)
# plt.figure(figsize = (10,7))
# sn.heatmap(matrix, annot=True, fmt='g')

In [4]:
# 102400 - 1-fold
paths_1 = [f'/gpt2/all.limit-102400.chunk-32.epochs-{i}.batch-160/results.csv' for i in range(1, 5+1)]

for p in paths_1:
    print(p)
    results(p)    
    print('---')

/gpt2/all.limit-102400.chunk-32.epochs-1.batch-160/results.csv
len(references) 1083


good 1075
bad 8
matrix [[154   0   0   0   0   0   0   0   0]
 [  1 246   0   0   0   0   0   0   0]
 [  0   0 294   0   0   0   0   0   0]
 [  0   0   0  47   0   0   0   0   0]
 [  0   1   0   0   3   0   0   0   0]
 [  0   0   0   0   0  75   0   0   0]
 [  1   0   0   0   0   0  37   1   0]
 [  2   1   0   0   0   0   0 118   1]
 [  0   0   0   0   0   0   0   0 101]]
acc f1
0,9926;0,9872;0,9939;1,0;1,0;0,8571;1,0;0,9737;0,9793;0,9951
---
/gpt2/all.limit-102400.chunk-32.epochs-2.batch-160/results.csv
len(references) 1083
good 1076
bad 7
matrix [[154   0   0   0   0   0   0   0   0]
 [  1 246   0   0   0   0   0   0   0]
 [  0   0 294   0   0   0   0   0   0]
 [  0   0   0  47   0   0   0   0   0]
 [  0   1   0   0   3   0   0   0   0]
 [  0   0   0   0   0  75   0   0   0]
 [  1   0   0   0   0   0  37   1   0]
 [  1   1   0   0   0   0   0 119   1]
 [  0   0   0   0   0   0   0   0 101]]
acc f1
0,9935;0,9904;0,9939;1,0;1,0;0,8571;1,0;0,9737;0,9835;0,9951
---
/gpt2/all.limit-102400

In [ ]:
# 10240 - 10-fold
paths_2 = [f'/gpt2/all.limit-10240.fold-{i}.chunk-32.epochs-1.batch-160/results.csv' for i in range(1, 10+1)]

for p in paths_2:
    print(p)
    results(p)    
    print('---')

/gpt2/all.limit-10240.fold-1.chunk-32.epochs-1.batch-160/results.csv
len(references) 1083
good 1069
bad 14
acc f1
0,9871;0,9646;0,9919;0,9983;1,0;0,8571;1,0;0,9737;0,9669;0,995
---
/gpt2/all.limit-10240.fold-2.chunk-32.epochs-1.batch-160/results.csv
len(references) 1120
good 839
bad 281
acc f1
0,7491;0,9169;0,0309;0,995;0,9623;1,0;0,8571;0,9783;0,533;0,8571
---
/gpt2/all.limit-10240.fold-3.chunk-32.epochs-1.batch-160/results.csv
len(references) 1081
good 1067
bad 14
acc f1
0,987;0,9642;0,998;1,0;0,9895;0,6667;1,0;1,0;0,9627;0,9802
---
/gpt2/all.limit-10240.fold-4.chunk-32.epochs-1.batch-160/results.csv
len(references) 1083
good 1062
bad 21
acc f1
0,9806;0,9506;0,998;1,0;0,9691;1,0;0,9933;0,96;0,9264;0,995
---
/gpt2/all.limit-10240.fold-5.chunk-32.epochs-1.batch-160/results.csv
len(references) 1080
good 1063
bad 17
acc f1
0,9843;0,9646;0,9879;0,9983;0,9691;1,0;0,9796;0,987;0,9664;0,995
---
/gpt2/all.limit-10240.fold-6.chunk-32.epochs-1.batch-160/results.csv
len(references) 1083
good 106

In [ ]:
# 102400 - 10-fold
paths_3 = [f'/gpt2/all.limit-102400.fold-{i}.chunk-32.epochs-1.batch-160/results.csv' for i in range(1, 10+1)]

for p in paths_3:
    print(p)
    results(p)    
    print('---')

/gpt2/all.limit-102400.fold-1.chunk-32.epochs-1.batch-160/results.csv
len(references) 1083
good 1075
bad 8
acc f1
0,9926;0,9872;0,9939;1,0;1,0;0,8571;1,0;0,9737;0,9793;0,9951
---
/gpt2/all.limit-102400.fold-2.chunk-32.epochs-1.batch-160/results.csv
len(references) 1120
good 1097
bad 23
acc f1
0,9795;0,9623;0,9921;1,0;0,9623;0,9091;0,9595;0,967;0,9457;0,9904
---
/gpt2/all.limit-102400.fold-3.chunk-32.epochs-1.batch-160/results.csv
len(references) 1081
good 1071
bad 10
acc f1
0,9907;0,9677;0,998;1,0;1,0;0,8571;1,0;1,0;0,9791;0,9851
---
/gpt2/all.limit-102400.fold-4.chunk-32.epochs-1.batch-160/results.csv
len(references) 1083
good 1063
bad 20
acc f1
0,9815;0,9533;0,996;1,0;0,9691;1,0;0,9933;0,96;0,9356;0,995
---
/gpt2/all.limit-102400.fold-5.chunk-32.epochs-1.batch-160/results.csv
len(references) 1080
good 1066
bad 14
acc f1
0,987;0,9712;0,9939;0,9983;0,9691;1,0;0,9865;0,987;0,9707;0,99
---
/gpt2/all.limit-102400.fold-6.chunk-32.epochs-1.batch-160/results.csv
len(references) 1083
good 106

# Tensorboard

In [ ]:
# %load_ext tensorboard
# %tensorboard --logdir /content/drive/Shareddrives/GPTJ/data/gpt2/7.limit-256.chunk-32.epochs-5.batch-16/logs